#!/usr/bin/env python
# -*- coding: UTF-8 -*-
#
# generated by wxGlade 0.6.8 on Sat Nov  1 13:19:14 2014
#
import wx
from controller import Controller
# begin wxGlade: dependencies
import gettext
# end wxGlade

# begin wxGlade: extracode
from customWidgets import EventCheckListCtrl
from customWidgets import SatzCheckListCtrl
from customWidgets import PlotPanel
from customWidgets import SchuetzenListCtrl
# end wxGlade

class MainFrame(wx.Frame):
    def __init__(self, controller, *args, **kwds):
        # begin wxGlade: MainFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.frame_1_menubar = wx.MenuBar()
        wxglade_tmp_menu = wx.Menu()
        self.DateChangeAbleMenu = wx.MenuItem(wxglade_tmp_menu, wx.ID_ANY, _(u"Datum frei w\xe4hlbar"), "", wx.ITEM_CHECK)
        wxglade_tmp_menu.AppendItem(self.DateChangeAbleMenu)
        self.DeleteEnableMenu = wx.MenuItem(wxglade_tmp_menu, wx.ID_ANY, _(u"L\xf6schen erlauben"), "", wx.ITEM_CHECK)
        wxglade_tmp_menu.AppendItem(self.DeleteEnableMenu)
        self.frame_1_menubar.Append(wxglade_tmp_menu, _("Optionen"))
        self.SetMenuBar(self.frame_1_menubar)
        # Menu Bar end
        self.notebook_1 = wx.Notebook(self, wx.ID_ANY, style=0)
        self.notebook_1_pane_Eingabe = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.label_5 = wx.StaticText(self.notebook_1_pane_Eingabe, wx.ID_ANY, _(u"Sch\xfctze"))
        self.combo_box_schuetze = wx.ComboBox(self.notebook_1_pane_Eingabe, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN | wx.CB_READONLY | wx.CB_SORT)
        self.label_ringe = wx.StaticText(self.notebook_1_pane_Eingabe, wx.ID_ANY, _("Ringe"))
        self.text_ctrl_satz = wx.TextCtrl(self.notebook_1_pane_Eingabe, wx.ID_ANY, "")
        self.label_datum = wx.StaticText(self.notebook_1_pane_Eingabe, wx.ID_ANY, _("Datum"))
        self.datepicker_ctrl_eintrag = wx.DatePickerCtrl(self.notebook_1_pane_Eingabe, wx.ID_ANY)
        self.panel_5 = wx.Panel(self.notebook_1_pane_Eingabe, wx.ID_ANY)
        self.button_eintragen = wx.Button(self.notebook_1_pane_Eingabe, wx.ID_ANY, _("Eintragen"))
        self.notebook_1_pane_pro_termin = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.label_4 = wx.StaticText(self.notebook_1_pane_pro_termin, wx.ID_ANY, _("Termin"))
        self.combo_box_stats_pro_termin = wx.ComboBox(self.notebook_1_pane_pro_termin, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.SchuetzenListCtrl = SchuetzenListCtrl(self.notebook_1_pane_pro_termin, [["Noname", "-","-","-","-", "----"]])
        self.notebook_1_pane_grafik = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.label_1 = wx.StaticText(self.notebook_1_pane_grafik, wx.ID_ANY, _("Plot"), style=wx.ALIGN_CENTRE)
        self.combo_box_plot_mode = wx.ComboBox(self.notebook_1_pane_grafik, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.label_2 = wx.StaticText(self.notebook_1_pane_grafik, wx.ID_ANY, _("Start"), style=wx.ST_NO_AUTORESIZE)
        self.combo_box_plot_start = wx.ComboBox(self.notebook_1_pane_grafik, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.label_3 = wx.StaticText(self.notebook_1_pane_grafik, wx.ID_ANY, _("Ende"))
        self.combo_box_plot_end = wx.ComboBox(self.notebook_1_pane_grafik, wx.ID_ANY, choices=[], style=wx.CB_DROPDOWN)
        self.sizer_4_staticbox = wx.StaticBox(self.notebook_1_pane_grafik, wx.ID_ANY, "")
        self.panel_matplotlib = PlotPanel(self.notebook_1_pane_grafik, wx.ID_ANY)
        self.notebook_1_pane_3 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.panel_1 = wx.Panel(self.notebook_1_pane_3, wx.ID_ANY, style=wx.RAISED_BORDER | wx.TAB_TRAVERSAL)
        self.label_6 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Vorname"), style=wx.ALIGN_CENTRE)
        self.text_ctrl_new_name = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.label_7 = wx.StaticText(self.panel_1, wx.ID_ANY, _("Nachname"))
        self.text_ctrl_new_surname = wx.TextCtrl(self.panel_1, wx.ID_ANY, "")
        self.panel_3 = wx.Panel(self.panel_1, wx.ID_ANY)
        self.button_neu_erstellen = wx.Button(self.panel_1, wx.ID_ANY, _("Erstellen"))
        self.panel_2 = wx.Panel(self.notebook_1_pane_3, wx.ID_ANY, style=wx.RAISED_BORDER | wx.TAB_TRAVERSAL)
        self.label_8 = wx.StaticText(self.panel_2, wx.ID_ANY, _("Name"))
        self.choice_delete = wx.Choice(self.panel_2, wx.ID_ANY, choices=[])
        self.panel_4 = wx.Panel(self.panel_2, wx.ID_ANY)
        self.button_delete = wx.Button(self.panel_2, wx.ID_ANY, _(u"L\xf6schen"))
        self.SatzDeleteListCtrl = SatzCheckListCtrl(self.notebook_1_pane_3, wx.ID_ANY)
        self.satz_delete = wx.Button(self.notebook_1_pane_3, wx.ID_ANY, _(u"S\xe4tze L\xf6schen"))
        self.notebook_1_pane_1 = wx.Panel(self.notebook_1, wx.ID_ANY)
        self.panel_6 = wx.Panel(self.notebook_1_pane_1, wx.ID_ANY, style=wx.RAISED_BORDER | wx.TAB_TRAVERSAL)
        self.label_10 = wx.StaticText(self.panel_6, wx.ID_ANY, _("Beschreibung"))
        self.text_ctrl_event_description = wx.TextCtrl(self.panel_6, wx.ID_ANY, "")
        self.label_11 = wx.StaticText(self.panel_6, wx.ID_ANY, _("Datum"))
        self.datepicker_ctrl_event = wx.DatePickerCtrl(self.panel_6, wx.ID_ANY)
        self.panel_7 = wx.Panel(self.panel_6, wx.ID_ANY)
        self.button_event_add = wx.Button(self.panel_6, wx.ID_ANY, _("Eintragen"))
        self.panel_8 = wx.Panel(self.notebook_1_pane_1, wx.ID_ANY, style=wx.RAISED_BORDER | wx.TAB_TRAVERSAL)
        self.EventDeleteCtrl = EventCheckListCtrl(self.panel_8, wx.ID_ANY)
        self.button_event_delete = wx.Button(self.panel_8, wx.ID_ANY, _(u"Ereignisse l\xf6schen"))

        self.__set_properties()
        self.__do_layout()

        self.Bind(wx.EVT_MENU, self.OnDateEditableChange, self.DateChangeAbleMenu)
        self.Bind(wx.EVT_MENU, self.OnDeleteEnable, self.DeleteEnableMenu)
        self.Bind(wx.EVT_BUTTON, self.OnEintrag, self.button_eintragen)
        self.Bind(wx.EVT_COMBOBOX, self.OnChangeStatsTermin, self.combo_box_stats_pro_termin)
        self.Bind(wx.EVT_COMBOBOX, self.OnPlotModeChange, self.combo_box_plot_mode)
        self.Bind(wx.EVT_COMBOBOX, self.OnPlotModeChange, self.combo_box_plot_start)
        self.Bind(wx.EVT_COMBOBOX, self.OnPlotModeChange, self.combo_box_plot_end)
        self.Bind(wx.EVT_BUTTON, self.OnCreate, self.button_neu_erstellen)
        self.Bind(wx.EVT_BUTTON, self.OnDelete, self.button_delete)
        self.Bind(wx.EVT_BUTTON, self.OnSatzDelete, self.satz_delete)
        self.Bind(wx.EVT_BUTTON, self.OnEventEntry, self.button_event_add)
        self.Bind(wx.EVT_BUTTON, self.OnEventDelete, self.button_event_delete)
        # end wxGlade
        self.controller = controller
        self.controller.set_mainframe(self)

    def __set_properties(self):
        # begin wxGlade: MainFrame.__set_properties
        self.SetTitle(_("Schuss'N Ofen Stats"))
        self.SetSize((978, 656))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: MainFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.VERTICAL)
        sizer_8 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_5 = wx.FlexGridSizer(3, 2, 0, 0)
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_7 = wx.BoxSizer(wx.VERTICAL)
        grid_sizer_1 = wx.FlexGridSizer(1, 2, 0, 100)
        grid_sizer_4 = wx.FlexGridSizer(2, 2, 0, 0)
        grid_sizer_2 = wx.FlexGridSizer(4, 2, 0, 0)
        sizer_2 = wx.BoxSizer(wx.VERTICAL)
        self.sizer_4_staticbox.Lower()
        sizer_4 = wx.StaticBoxSizer(self.sizer_4_staticbox, wx.HORIZONTAL)
        sizer_3 = wx.BoxSizer(wx.VERTICAL)
        sizer_5 = wx.BoxSizer(wx.HORIZONTAL)
        grid_sizer_3 = wx.FlexGridSizer(4, 2, 0, 0)
        grid_sizer_3.Add(self.label_5, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_3.Add(self.combo_box_schuetze, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.label_ringe, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_3.Add(self.text_ctrl_satz, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.label_datum, 0, wx.ALL | wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_3.Add(self.datepicker_ctrl_eintrag, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_3.Add(self.panel_5, 1, wx.EXPAND, 0)
        grid_sizer_3.Add(self.button_eintragen, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.notebook_1_pane_Eingabe.SetSizer(grid_sizer_3)
        sizer_5.Add(self.label_4, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_5.Add(self.combo_box_stats_pro_termin, 0, 0, 0)
        sizer_3.Add(sizer_5, 0, wx.EXPAND, 0)
        sizer_3.Add(self.SchuetzenListCtrl, 1, wx.EXPAND, 0)
        self.notebook_1_pane_pro_termin.SetSizer(sizer_3)
        sizer_4.Add(self.label_1, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_4.Add(self.combo_box_plot_mode, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(self.label_2, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_4.Add(self.combo_box_plot_start, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_4.Add(self.label_3, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        sizer_4.Add(self.combo_box_plot_end, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        sizer_2.Add(sizer_4, 0, wx.EXPAND, 0)
        sizer_2.Add(self.panel_matplotlib, 1, wx.EXPAND, 0)
        self.notebook_1_pane_grafik.SetSizer(sizer_2)
        grid_sizer_2.Add(self.label_6, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_2.Add(self.text_ctrl_new_name, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.label_7, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_2.Add(self.text_ctrl_new_surname, 0, wx.EXPAND, 0)
        grid_sizer_2.Add(self.panel_3, 1, wx.EXPAND, 0)
        grid_sizer_2.Add(self.button_neu_erstellen, 0, 0, 0)
        self.panel_1.SetSizer(grid_sizer_2)
        grid_sizer_1.Add(self.panel_1, 1, wx.EXPAND, 0)
        grid_sizer_4.Add(self.label_8, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_4.Add(self.choice_delete, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_4.Add(self.panel_4, 1, wx.EXPAND, 0)
        grid_sizer_4.Add(self.button_delete, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        self.panel_2.SetSizer(grid_sizer_4)
        grid_sizer_1.Add(self.panel_2, 1, wx.EXPAND, 0)
        sizer_6.Add(grid_sizer_1, 0, wx.EXPAND, 0)
        sizer_7.Add(self.SatzDeleteListCtrl, 1, wx.EXPAND, 0)
        sizer_7.Add(self.satz_delete, 0, 0, 0)
        sizer_6.Add(sizer_7, 1, wx.EXPAND, 0)
        self.notebook_1_pane_3.SetSizer(sizer_6)
        grid_sizer_5.Add(self.label_10, 0, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        grid_sizer_5.Add(self.text_ctrl_event_description, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.label_11, 0, wx.ALL, 5)
        grid_sizer_5.Add(self.datepicker_ctrl_event, 0, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 0)
        grid_sizer_5.Add(self.panel_7, 1, wx.EXPAND, 0)
        grid_sizer_5.Add(self.button_event_add, 0, 0, 0)
        self.panel_6.SetSizer(grid_sizer_5)
        sizer_8.Add(self.panel_6, 1, wx.ALL | wx.ALIGN_CENTER_HORIZONTAL, 5)
        sizer_9.Add(self.EventDeleteCtrl, 1, wx.ALL | wx.EXPAND, 5)
        sizer_9.Add(self.button_event_delete, 0, wx.ALL, 4)
        self.panel_8.SetSizer(sizer_9)
        sizer_8.Add(self.panel_8, 3, wx.ALL | wx.EXPAND | wx.ALIGN_CENTER_HORIZONTAL | wx.ALIGN_CENTER_VERTICAL, 5)
        self.notebook_1_pane_1.SetSizer(sizer_8)
        self.notebook_1.AddPage(self.notebook_1_pane_Eingabe, _("Eingabe"))
        self.notebook_1.AddPage(self.notebook_1_pane_pro_termin, _("Statistiken"))
        self.notebook_1.AddPage(self.notebook_1_pane_grafik, _("Grafiken"))
        self.notebook_1.AddPage(self.notebook_1_pane_3, _("Verwaltung"))
        self.notebook_1.AddPage(self.notebook_1_pane_1, _("Ereignisse"))
        sizer_1.Add(self.notebook_1, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

    def OnChangeSchuetze(self, event):  # wxGlade: MainFrame.<event_handler>
        print "Event handler 'OnChangeSchuetze' not implemented!"
        event.Skip()
    def OnEintrag(self, event):  # wxGlade: MainFrame.<event_handler>
        self.controller.OnEintrag(event)

    def OnChangeStatsTermin(self, event):  # wxGlade: MainFrame.<event_handler>
        self.controller.OnChangeStatsTermin(event)
        
    def OnPlotModeChange(self, event):  # wxGlade: MainFrame.<event_handler>
        self.controller.OnPlotModeChange(event)
        
    def OnCreate(self, event):  # wxGlade: MainFrame.<event_handler>
        self.controller.OnCreate(event)

    def OnDelete(self, event):  # wxGlade: MainFrame.<event_handler>
        print "Function not implemented. TODO look how to get value of choice."
        self.controller.OnDelete(event)

    def OnDateEditableChange(self, event):  # wxGlade: MainFrame.<event_handler>
        self.controller.OnDateEditableChange(event)

    def OnSatzDelete(self, event):  # wxGlade: MainFrame.<event_handler>
        self.controller.OnSatzDelete(event)
        
    def OnDeleteEnable(self, event):  # wxGlade: MainFrame.<event_handler>
        self.controller.OnDeleteEnable(event)
        
    def OnEventEntry(self, event):  # wxGlade: MainFrame.<event_handler>
        self.controller.OnEventEntry(event)

    def OnEventDelete(self, event):  # wxGlade: MainFrame.<event_handler>
        self.controller.OnEventDelete(event)
        
# end of class MainFrame
if __name__ == "__main__":
    gettext.install("app") # replace with the appropriate catalog name

    app = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    frame_1 = MainFrame(Controller(), None, wx.ID_ANY, "")
    app.SetTopWindow(frame_1)
    frame_1.Show()
    app.MainLoop()